namespace: freshrss-application

_shared_config:
  hostname: &hostname freshrss-application.staging.k8s.webgrip.nl
  url: &url https://freshrss-application.staging.k8s.webgrip.nl

freshrss:
  image:
    repository: webgrip/freshrss-application
    tag: latest
    pullPolicy: Always

  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      primary: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-traefik
  #      traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-ryan-basic-auth@kubernetescrd"
      labels:
        app.kubernetes.io/name: freshrss-application
        app.kubernetes.io/instance: freshrss-application
      ingressClassName: ingress-traefik
      hosts:
        - host: *hostname
          paths:
            - path: /
              pathType: Prefix
              service:
                name: freshrss-application
                port: 80
      tls:
        - secretName: letsencrypt-freshrss-application
          hosts:
            - *hostname
      
  # https://github.com/linuxserver/docker-freshrss#parameters
  env:
    TZ: Europe/Amsterdam
    PUID: "568"
    PGID: "568"
    CRON_MINUTE: "1,11,21,31,41,51"
