<?php
declare(strict_types=1);
/** @var TogglableMenuExtension $this */
// TODO: Update to parent::getUserConfigurationValue() methods:
$minWidth = FreshRSS_Context::userConf()->TogglableMenu['menu_display_width_threshold'] ?? 840;
?>

<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
	<div class="form-group">
		<label class="group-name" for="togglablemenu_min_width" title="<?= _t('ext.TogglableMenu.menu_display_width_threshold') ?>"><?= _t('ext.TogglableMenu.menu_display_width_threshold') ?></label>
		<div class="group-controls">
		<input
			type="number"
			step="1"
			name="togglablemenu_min_width"
			id="togglablemenu_min_width"
			value="<?= $minWidth ?>"
			/>
		</div>
        </div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>
