FROM ghcr.io/linuxserver/freshrss:1.26.3-ls277@sha256:956682095c65d891ef4d85736ce6dbaf562710fa1210aeb7c2415898022b4cae

COPY ops/docker/application/extensions/ /config/www/freshrss/extensions

# COPY ops/docker/application/config.custom.php /config/www/freshrss/data/config.custom.php
# COPY ops/docker/application/config-user.custom.php /config/www/freshrss/data/config-user.custom.php
