FROM ghcr.io/linuxserver/freshrss:1.26.3-ls277

COPY ops/docker/application/extensions/ /config/www/freshrss/extensions

# COPY ops/docker/application/config.custom.php /config/www/freshrss/data/config.custom.php
# COPY ops/docker/application/config-user.custom.php /config/www/freshrss/data/config-user.custom.php
