FROM freshrss/freshrss:edge-alpine

COPY ops/docker/application/extensions/ /var/www/FreshRSS/extensions/

COPY ops/docker/application/config.custom.php /var/www/FreshRSS/data/config.custom.php
COPY ops/docker/application/config-user.custom.php /var/www/FreshRSS/data/config-user.custom.php