FROM freshrss/freshrss:edge-alpine@sha256:57a3943f9815f862bdb237399e97ebd1e50c3865934e4d1ce2f4df051c9fd24d

COPY ops/docker/application/extensions/ /var/www/FreshRSS/extensions/

COPY ops/docker/application/config.custom.php /var/www/FreshRSS/data/config.custom.php
COPY ops/docker/application/config-user.custom.php /var/www/FreshRSS/data/config-user.custom.php